feat: get log streams
jcloudify/jcloudify-api pull request #103
Opened 2024-09-02 19:55 UTC by Onitsiky

2024-09-03 06:44 UTC, Mahefaa requested changes

2024-09-03 06:44 UTC, Mahefaa commented on doc/api.yml
> +      operationId: getLogStreams
getFunctionLogStreams

2024-09-03 06:44 UTC, Mahefaa commented on src/test/java/api/jcloudify/app/integration/ApplicationEnvironmentLogIT.java
> +  private static final Logger log = LoggerFactory.getLogger(ApplicationEnvironmentLogIT.class);
what is this? use `@slf4j`

2024-09-03 06:44 UTC, Mahefaa commented on src/test/java/api/jcloudify/app/integration/ApplicationEnvironmentLogIT.java
> +    String logGroupName = encode(PROD_COMPUTE_FRONTAL_FUNCTION_LOG_GROUP, UTF_8);
unused var

2024-09-04 06:48 UTC, Mahefaa requested changes

2024-09-04 06:48 UTC, Mahefaa commented on src/main/java/api/jcloudify/app/endpoint/rest/controller/ApplicationEnvironmentController.java
> +  private PagedLogStreams getLogStreams(
private?

2024-09-04 06:48 UTC, Mahefaa commented on cf-stacks/scheduler-stack.yml
> +        - 'arn:aws:iam::aws:policy/AdministratorAccess'
do we really need AdministratorAccess here?

2024-09-04 06:48 UTC, Mahefaa commented on cf-stacks/scheduler-stack.yml
> +          DetailType: 'api.jcloudify.app.endpoint.event.model.RefreshUserLogStreamsTriggered'
the main Event will refresh ALL users, hence RefreshUsersLogStreamsTriggered, which will be divided into multiple RefreshUserLogStreams event. note the diff between the former and the latter. ( the former is for Users, the latter is for User)

2024-09-04 06:48 UTC, Mahefaa commented on src/main/java/api/jcloudify/app/endpoint/rest/controller/ApplicationEnvironmentController.java
> +  private PagedLogStreams getLogStreams(
name it getFunctionLogStreams ( like openapi operationId)

2024-09-04 06:48 UTC, Mahefaa commented on src/main/java/api/jcloudify/app/endpoint/rest/controller/ApplicationEnvironmentController.java
> +      @RequestParam String logGroupName,
logGroupName requestParam is required ?

2024-09-04 06:48 UTC, Mahefaa commented on src/main/java/api/jcloudify/app/service/LambdaFunctionLogService.java
> +      throw new RuntimeException(e);
if this exception occurs in API calls, you are supposed to use API errors

2024-09-04 06:48 UTC, Mahefaa commented on src/main/java/api/jcloudify/app/service/LambdaFunctionLogService.java
> +      throw new RuntimeException(e);
otherwise, leave it as is

2024-09-04 06:48 UTC, Mahefaa commented on src/main/java/api/jcloudify/app/service/LambdaFunctionLogService.java
> +  private static <T> Set<T> mergeLists(List<T> list1, List<T> list2) {
mergeListToSet

2024-09-04 07:00 UTC, Onitsiky commented on cf-stacks/scheduler-stack.yml
> +        - 'arn:aws:iam::aws:policy/AdministratorAccess'
I did not check the policy we need actually, soo

2024-09-04 07:02 UTC, Onitsiky commented on src/main/java/api/jcloudify/app/endpoint/rest/controller/ApplicationEnvironmentController.java
> +      @RequestParam String logGroupName,
yup

2024-09-04 07:19 UTC, merged