feat: app loogs
jcloudify/jcloudify-api pull request #105
Opened 2024-09-04 12:16 UTC by Onitsiky

2024-09-04 13:58 UTC, Mahefaa requested changes

2024-09-04 13:58 UTC, Mahefaa commented on cf-stacks/scheduler-stack.yml
> +      Description: Scheduler that trigger the refresh of user log stream events
typo: triggers*

2024-09-04 13:58 UTC, Mahefaa commented on src/main/java/api/jcloudify/app/service/event/RefreshUsersLogStreamEventsTriggeredService.java
> +    users.forEach(this::crupdateUserLogStreamEvents);
do you think this is do-able in 15 minutes?

2024-09-05 05:31 UTC, Onitsiky commented on src/main/java/api/jcloudify/app/service/event/RefreshUsersLogStreamEventsTriggeredService.java
> +    users.forEach(this::crupdateUserLogStreamEvents);
For a first try I can assure it will be do-able event in less than 10 mins

2024-09-05 05:39 UTC, merged