chore: add new state for deployment
jcloudify/jcloudify-api pull request #181
Opened 2024-11-13 06:51 UTC by Onitsiky

2024-11-13 16:46 UTC, Mahefaa commented on src/main/java/api/jcloudify/app/service/pojaConfHandler/Poja1UploadedHandler.java
>      }
merge catch blocks and rm the log.info

2024-11-13 16:46 UTC, Mahefaa commented
drop [chore: catch SesException](https://github.com/jcloudify/jcloudify-api/pull/181/commits/115cb740aebd9b0a6e61e3235ab961b6cfc403d6)

2024-11-15 11:52 UTC, Mahefaa requested changes

2024-11-15 11:52 UTC, Mahefaa commented on doc/env-deploy-api.yml
> +          $ref: "./application-api.yml#/components/schemas/DeploymentStateEnum"
too many possible values for a github workflow state, create its own rest state then map into ours

2024-11-15 11:52 UTC, Mahefaa commented on src/main/java/api/jcloudify/app/mail/Mailer.java
drop

2024-11-15 11:52 UTC, Mahefaa commented on src/main/java/api/jcloudify/app/service/EnvironmentBuildService.java
> +    actual.toBuilder()
return here instead of returning actual down there

2024-11-15 11:52 UTC, Mahefaa commented on src/main/java/api/jcloudify/app/service/EnvironmentBuildService.java
> +    actual.toBuilder()
return on line 75

2024-11-15 11:52 UTC, Mahefaa commented on src/main/java/api/jcloudify/app/service/EnvironmentBuildService.java
> +    Pattern pattern = Pattern.compile("long ID:\\s*(\\S+)");
compile pattern as a static variable as this is pretty heavy yet reusable

2024-11-15 11:52 UTC, Mahefaa commented on src/main/java/api/jcloudify/app/service/EnvironmentBuildService.java
> +    Pattern pattern = Pattern.compile("long ID:\\s*(\\S+)");
ok add additional verification to separate jc-bot-made commits from normal commits.

if jc bot commits, do the verification with long Id and stuff
otherwise do something else

2024-11-15 11:52 UTC, Mahefaa commented on src/main/java/api/jcloudify/app/service/EnvironmentBuildService.java
> +    Pattern pattern = Pattern.compile("long ID:\\s*(\\S+)");
it will help reduce your condition complexity

2024-11-15 11:52 UTC, Mahefaa commented on src/main/java/api/jcloudify/app/service/EnvironmentBuildService.java
> +    throw new BadRequestException("Invalid commitMessage");
only throw this if jcBot and commit does not contain the id

2024-11-15 11:52 UTC, Mahefaa commented on src/main/java/api/jcloudify/app/service/EnvironmentBuildService.java
> +    throw new BadRequestException("Invalid commitMessage");
also, make sure not to loop this event by throwing exceptions, if this code is meant to be used in a worker, you can try catch **WHERE IT IS USED** and log.error instead

2024-11-15 11:52 UTC, Mahefaa commented on src/main/java/api/jcloudify/app/service/appEnvConfigurer/AppEnvConfigurerService.java
> +        new PojaConfUploaded(pojaVersion, environmentId, userId, nonFormattedFilename, appId, null);
why null ????

2024-11-15 11:52 UTC, Mahefaa commented on src/main/java/api/jcloudify/app/service/appEnvConfigurer/AppEnvConfigurerService.java
> +        new PojaConfUploaded(pojaVersion, environmentId, userId, nonFormattedFilename, appId, null);
if it will always be null then do not mind adding it to the Class

2024-11-18 08:11 UTC, Onitsiky commented on src/main/java/api/jcloudify/app/service/EnvironmentBuildService.java
> +    throw new BadRequestException("Invalid commitMessage");
This won't run in any worker

2024-11-18 10:08 UTC, Mahefaa requested changes

2024-11-18 10:08 UTC, Mahefaa commented on src/main/java/api/jcloudify/app/service/EnvironmentBuildService.java
> +  private final String JCLOUDIFY_BOT_COMMIT_PATTERN = "long ID:\\s*(\\S+)";
compile here not down there

2024-11-18 10:08 UTC, Mahefaa commented on src/main/java/api/jcloudify/app/service/EnvironmentBuildService.java
> +        }
NotFound check seems irrelevant

2024-11-18 10:08 UTC, Mahefaa commented on src/main/java/api/jcloudify/app/service/EnvironmentBuildService.java
> +          || (matcher.find() && !JCLOUDIFY_BOT_USERNAME.equals(state.getCommitAuthorName()))) {
store matcher.find() in a variable and reuse it

2024-11-18 10:08 UTC, Mahefaa commented on src/main/java/api/jcloudify/app/service/event/PojaConfUploadedService.java
> +      pojaConfUploaded.toBuilder().appEnvDeploymentId(savedAppEnvDeploymentId).build();
needs to be assigned to a variable in order to be used

2024-11-19 05:43 UTC, Mahefaa requested changes

2024-11-19 05:43 UTC, Mahefaa commented on src/main/java/api/jcloudify/app/repository/model/AppEnvironmentDeployment.java
> +        if (newStatus == CODE_PUSH_IN_PROGRESS) {
flip equals

2024-11-19 05:43 UTC, Mahefaa commented on src/main/java/api/jcloudify/app/service/EnvironmentBuildService.java
> +        throw new BadRequestException("Invalid commitMessage");
put line 110 ~120 in a method named handleJcloudifyBotCommit

2024-11-19 05:43 UTC, Mahefaa commented on src/main/java/api/jcloudify/app/service/EnvironmentBuildService.java
> +        savePreviousDeploymentStates(appEnvironmentDeployment.getId());
line 122~124 handleUser commit

2024-11-19 07:19 UTC, merged